interFAX:
  scheme: "https"
  hostname: "rest.interfax.net"
  port: 443
  outboundFaxesEndpoint: "/outbound/faxes"
  outboundFaxesCompletedEndpoint: "/outbound/faxes/completed"
  outboundFaxesRecordEndpoint: "/outbound/faxes/%s"
  outboundFaxImageEndpoint: "/outbound/faxes/%s/image"
  outboundFaxesCancelEndpoint: "/outbound/faxes/%s/cancel"
  outboundFaxesResendEndpoint: "/outbound/faxes/%s/resend"
  outboundFaxesHideEndpoint: "/outbound/faxes/%s/hide"
  outboundSearchEndpoint: "/outbound/search"
  outboundDocumentsEndpoint: "/outbound/documents"
  accountsBalanceEndpoint: "/accounts/self/ppcards/balance"
  inboundFaxesEndpoint: "/inbound/faxes"
  inboundFaxesImageEndpoint: "/inbound/faxes/%s/image"
  inboundFaxesEmailsEndpoint: "/inbound/faxes/%s/emails"